/* objects for entire program */

#include "..\core\rgbdefs.h"

GLOBALVARIABLE HBRUSH obj_hbr_black;
GLOBALVARIABLE HBRUSH obj_hbr_white;
GLOBALVARIABLE HBRUSH obj_hbr_liteblue;
GLOBALVARIABLE HBRUSH obj_hbr_litered;
GLOBALVARIABLE HBRUSH obj_hbr_litegreen;
GLOBALVARIABLE HBRUSH obj_hbr_yellow;
GLOBALVARIABLE HBRUSH obj_hbr_darkgray;
GLOBALVARIABLE HBRUSH obj_hbr_cyan;
GLOBALVARIABLE HBRUSH obj_hbr_orange;
GLOBALVARIABLE HBRUSH obj_hbr_palecyan;
GLOBALVARIABLE HBRUSH obj_hbr_paleyellow;
GLOBALVARIABLE HBRUSH obj_hbr_olivegreen;
GLOBALVARIABLE HBRUSH obj_hbr_deepred;
GLOBALVARIABLE HBRUSH obj_hbr_litegray;
GLOBALVARIABLE HBRUSH obj_hbr_mud;
GLOBALVARIABLE HBRUSH obj_hbr_darkblue;
GLOBALVARIABLE HBRUSH obj_hbr_blackblue;
GLOBALVARIABLE HBRUSH obj_hbr_tealgreen;
GLOBALVARIABLE HBRUSH obj_hbr_palegreen;
//GLOBALVARIABLE HBRUSH obj_hbr_dlgback;


//GLOBALVARIABLE HCURSOR obj_hCursor_righthand;
GLOBALVARIABLE HCURSOR obj_hCursor_cross;
//GLOBALVARIABLE HCURSOR obj_hCursor_hourglass;
GLOBALVARIABLE HCURSOR obj_hCursor_arrow;
//GLOBALVARIABLE HCURSOR obj_hCursor_compass;

#ifdef IS_MAIN_PROGRAM_FILE
GLOBALVARIABLE LONG RGBblack = RGB(0,0,0);
GLOBALVARIABLE LONG RGBdarkgray = RGB(128,128,128);
GLOBALVARIABLE LONG RGBlitegray = RGB(192,192,192);
GLOBALVARIABLE LONG RGBwhite = RGB(255,255,255);
GLOBALVARIABLE LONG RGBlitered = RGB(255,0,0);
GLOBALVARIABLE LONG RGBdeepred = RGB(128,0,0);
GLOBALVARIABLE LONG RGBliteblue = RGB(0,0,255);
GLOBALVARIABLE LONG RGBdarkblue = RGB(0,0,128);
GLOBALVARIABLE LONG RGBblackblue = RGB(128,0,128);
GLOBALVARIABLE LONG RGBpaleyellow = RGB(255,255,128);
GLOBALVARIABLE LONG RGByellow = RGB(255,255,0);
GLOBALVARIABLE LONG RGBlitegreen = RGB(0,255,0);
GLOBALVARIABLE LONG RGBolivegreen = RGB(0,128,0);
GLOBALVARIABLE LONG RGBtealgreen = RGB(0,128,128);
GLOBALVARIABLE LONG RGBpalegreen = RGB(128,255,128);
GLOBALVARIABLE LONG RGBcyan = RGB(0,255,255);
GLOBALVARIABLE LONG RGBpalecyan = RGB(128,255,255);
GLOBALVARIABLE LONG RGBmud = RGB(128,128,0);
#else
GLOBALVARIABLE LONG RGBblack;
GLOBALVARIABLE LONG RGBdarkgray;
GLOBALVARIABLE LONG RGBlitegray;
GLOBALVARIABLE LONG RGBwhite;
GLOBALVARIABLE LONG RGBlitered;
GLOBALVARIABLE LONG RGBdeepred;
GLOBALVARIABLE LONG RGBliteblue;
GLOBALVARIABLE LONG RGBdarkblue;
GLOBALVARIABLE LONG RGBblackblue;
GLOBALVARIABLE LONG RGBpaleyellow;
GLOBALVARIABLE LONG RGBpaleyellow1;
GLOBALVARIABLE LONG RGByellow;
GLOBALVARIABLE LONG RGBlitegreen;
GLOBALVARIABLE LONG RGBolivegreen;
GLOBALVARIABLE LONG RGBtealgreen;
GLOBALVARIABLE LONG RGBpalegreen;
GLOBALVARIABLE LONG RGBcyan;
GLOBALVARIABLE LONG RGBpalecyan;
GLOBALVARIABLE LONG RGBmud;
#endif
