//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PQFWare.rc
//
#define AUX_20                          0
#define OPC_IDLE                        0
#define AUX_220                         1
#define OPC_CHARGING                    1
#define AUX_EXT                         2
#define OPC_READY                       2
#define OPC_DELAY                       3
#define IDD_PQFGRAPH_SCROLL             51
#define IDD_PQFGRAPH_DISPLAY            52
#define IDD_PQF_STANDBY                 100
#define IDD_PQF_EXIT                    101
#define IDD_EFT2M                       101
#define IDD_START_SB                    101
#define IDD_ABT_NAME                    101
#define IDD_EDIT                        101
#define LSDLG_APPEND                    101
#define IDC_BUT_RUN                     101
#define IDD_ILOCK_TEXT                  101
#define IDD_PQF_GRAPH                   102
#define IDD_EFT_TYPE                    102
#define IDD_STOP_SB                     102
#define IDD_SPIN                        102
#define LSDLG_REWRITE                   102
#define IDD_ABT_REV                     102
#define IDC_BUT_STOP                    102
#define IDD_CORRECT_TEXT                102
#define IDD_PQF_LIST                    103
#define IDD_SURGE_TYPE                  103
#define IDD_START_EDIT                  103
#define IDD_REPEAT_LAB                  103
#define LSDLG_INCNAME                   103
#define IDD_ABT_SN                      103
#define IDC_EDIT_LOG                    103
#define IDD_PQF_SIZEBOX                 104
#define IDD_SURGE_CPL                   104
#define IDD_STOP_EDIT                   104
#define IDD_ABT_LIST                    104
#define LSDLG_TEXT                      104
#define IDD_CHO_LIST                    104
#define IDD_ILOCK_DSCRP                 104
#define IDD_PQF_EUTPOWER                105
#define IDD_EFT_CPL                     105
#define IDD_STEPS_EDIT                  105
#define IDD_ABT_LABEL                   105
#define LSDLG_EXPORT                    105
#define IDD_PQF_EUTPOWER_GROUP          106
#define IDD_THREE_PHASE                 106
#define IDD_MODE1_CB                    106
#define IDD_PQF_EDITMODE                107
#define IDD_PQF_TYPE                    107
#define IDD_EXTRA_CB                    107
#define LSDLG_SELECT                    107
#define IDD_PQF_TESTMODE                108
#define IDD_POWER_TYPE                  108
#define IDD_EXTRA_TEXT                  108
#define LCDLG_TEXT                      108
#define IDD_PQF_MODE_BLOCK              109
#define IDD_AMP_TYPE                    109
#define IDD_TEXT_HI                     109
#define LSDLG_OPERATOR                  109
#define IDD_PQF_LINE_BLOCK              110
#define IDD_CAL_LIST                    110
#define IDD_ICON                        110
#define LSDLG_EUT                       110
#define IDD_PQF_PAUSE                   111
#define IDD_SINGLE_LB                   111
#define IDD_MAIN_LIST                   111
#define IDD_LIST                        111
#define LSDLG_COMMENT                   111
#define IDD_PQF_STEP                    112
#define IDD_STEP_BUTTON                 112
#define IDD_CB                          112
#define LSDLG_NOLOG                     112
#define IDD_PQF_STOP                    113
#define IDD_SET                         113
#define IDD_START_TXT                   113
#define IDD_PQF_RUN                     114
#define IDD_TRY                         114
#define IDD_STOP_TXT                    114
#define IDD_TOTAL_TEST                  114
#define IDD_PQF_ACTUALAC_BLOCK          115
#define IDD_DEFAULT                     115
#define IDD_STEPS_TXT                   115
#define IDD_COUPLER                     115
#define IDD_TOTAL_N                     115
#define LSDLG_NAME                      115
#define IDD_PQF_ACTUALAC_TEXT           116
#define IDD_SET_CAL                     116
#define IDD_MODE_TXT                    116
#define IDD_NAME_TEXT                   116
#define IDD_AUX                         116
#define IDD_MODE_TEXT                   116
#define IDD_PQF_ACTUAL_RMSI_TEXT        117
#define IDD_LEFT_MOD                    117
#define IDD_RUN_EDIT                    117
#define IDD_DATABTN                     117
#define IDD_ORDER                       117
#define IDD_PQF_ACTUAL_RMSI             118
#define IDD_RIGHT_MOD                   118
#define IDD_STEP_TXT2                   118
#define IDD_CMODEBTN                    118
#define IDD_PLUGIN                      118
#define IDD_PQF_ACTUAL_PEAKI_TEXT       119
#define IDD_MOD_SPIN                    119
#define IDD_RUN_TEXT                    119
#define IDD_COUPLER_TEXT                119
#define IDD_MAIN_FRAME                  119
#define IDD_WAVE                        119
#define IDD_PQF_ACTUAL_PEAKI            120
#define IDD_VM_SPIN                     120
#define IDD_SINGLE_SB                   120
#define IDD_AUX_TEXT                    120
#define IDD_RAW_STOP                    120
#define IDD_PQF_TIME_BLOCK              121
#define IDD_SPIN_MONTH                  121
#define IDD_SINGLE_EDIT                 121
#define IDD_DATA_TEXT                   121
#define IDD_RUN                         121
#define IDD_PQF_TIME_TEXT               122
#define IDD_SPIN_YEAR                   122
#define IDD_TEXT_LO                     122
#define IDD_EUT_GB                      122
#define IDD_PQF_TIME                    123
#define IDD_EXTRA_LAB                   123
#define IDD_TEXT                        123
#define IDD_PQF_TESTREPEAT              124
#define IDD_MODE_LAB                    124
#define IDD_DURATION_TEXT               124
#define IDD_PQF_LINE_VNOMINAL           125
#define IDD_NAME_COMBO                  125
#define IDD_WIN_TEXT                    125
#define IDD_PQF_LINE_VACTUAL            126
#define IDD_ID_EDIT                     126
#define IDD_PQF_LINE_FREQNOMINAL        127
#define IDD_CAL_EDIT                    127
#define IDD_TEST                        127
#define IDD_PQF_LINE_FREQACTUAL         128
#define IDD_MODULE_EDIT                 128
#define IDD_ACTION_TEXT                 128
#define IDD_PQF_LINEACTUAL_TEXT         129
#define IDD_SERN_EDIT                   129
#define IDD_TYPE_TEXT                   130
#define IDD_SRGCPL_TYPE                 131
#define IDD_WAIT_SB                     131
#define IDD_PQF_EDITTEXT                132
#define IDD_WAIT_EB                     132
#define IDD_PQF_LEVEL                   133
#define IDD_WAIT_CB                     133
#define IDD_PQF_LEVELEDIT               134
#define IDD_SAVE_CFG                    134
#define IDD_PQF_LEVELQUERY              135
#define IDD_IM_SPIN                     135
#define IDD_PQF_LEVELSCROLL             136
#define IDD_IM_TEXT                     136
#define IDD_PQF_STARTEDIT               137
#define IDD_VM_TEXT                     137
#define IDD_PQF_STARTQUERY              138
#define IDD_EFT_8KV                     138
#define IDD_PQF_STARTSCROLL             139
#define IDD_MISC                        139
#define IDD_PQF_DURATIONEDIT            140
#define IDD_EFT_CHIRP                   140
#define IDD_PQF_DURATIONUNITS           141
#define IDD_SRGDC                       141
#define IDD_PQF_DURATIONQUERY           142
#define IDD_ACOPT                       142
#define IDD_PQF_DURATIONSCROLL          143
#define IDD_SW_E502                     143
#define IDD_PQF_RMSIEDIT                144
#define IDD_DATACPL_TYPE                144
#define IDD_PQF_RMSIQUERY               145
#define IDD_IMPED_TYPE                  145
#define IDD_PQF_RMSISCROLL              146
#define IDD_ESD_TYPE                    146
#define IDD_PQF_PEAKIEDIT               147
#define IDD_EHVSUPPORT                  147
#define IDD_PQF_PEAKIQUERY              148
#define IDD_5CHAN                       148
#define IDD_PQF_PEAKISCROLL             149
#define IDD_ACCPL_TYPE                  149
#define IDD_PQF_INSERT                  150
#define IDD_HVCPL_TYPE                  150
#define IDD_PQF_REPLACE                 151
#define IDD_CLAMP_TYPE                  151
#define IDD_PQF_DELETE                  152
#define IDD_PQF_PHASEBOX                153
#define IDD_PQF_PHASEL1                 154
#define IDD_PQF_PHASEL2                 155
#define IDD_PQF_PHASEL3                 156
#define IDD_GND                         155
#define IDD_N                           156
#define IDD_PQF_PHASE_BLOCK             157
#define IDD_L1                          157
#define IDD_PQF_DELETE_ALL              157
#define IDD_PQF_PHASE_TEXT              158
#define IDD_L2                          158
#define IDD_L3                          159
#define IDD_PQF_COPY                    159
#define IDD_INVALID                     160
#define IDD_EUT                         161
#define IDD_EUT_POWER                   161
#define IDD_FRONT_LAB                   161
#define IDD_REPEAT                      162
#define IDD_REPEATDLG                   162
#define IDD_S1                          165
#define IDD_S2                          166
#define IDD_S3                          167
#define IDD_S4                          168
#define IDD_G                           169
#define IDD_PQF_CHEAT                   171
#define UPDATE_STEP                     200
#define IDD_PQF_LISTHDR                 201
#define IDD_PQF_TESTPLANHDR             202
#define IDD_PQF_STEPHDR                 203
#define IDD_PQF_LEVELHDR                204
#define IDD_VAL_SCROLL                  204
#define IDD_PQF_STARTHDR                205
#define IDD_VAL_EDIT                    205
#define IDD_PQF_DURATIONHDR             206
#define IDD_PQF_RMSILIMHDR              207
#define IDD_PQF_PEAKILIMHDR             208
#define IDD_PQF_ACLIMITSHDR             209
#define IDD_PQF_TOTALTIME               210
#define IDD_MEAS_BAY                    220
#define IDD_STOP                        220
#define IDD_VREADP                      221
#define IDD_VREADM                      222
#define IDD_IREADP                      223
#define IDD_IREADM                      224
#define IDD_VSETCB                      225
#define IDD_ISETCB                      226
#define IDD_VLAB1                       227
#define IDD_VLAB2                       228
#define IDD_ILAB1                       229
#define IDD_PKPLAB                      230
#define IDD_PKMLAB                      231
#define IDD_SETLAB                      232
#define IDD_ILAB2                       233
#define IDD_VSETP                       234
#define IDD_VSETM                       235
#define IDD_ISETP                       236
#define IDD_ISETM                       237
#define IDD_SETPLAB                     238
#define IDD_SETMLAB                     239
#define IDD_PVGT                        240
#define IDD_MVGT                        241
#define IDD_PIGT                        242
#define IDD_MIGT                        243
#define IDD_LIMIT_TEXT                  244
#define IDD_ECAT_EXIT                   245
#define IDD_ECAT_COMM                   246
#define IDD_GT                          250
#define IDD_RLIM                        253
#define IDD_PLIM                        254
#define IDD_PEAK1                       260
#define IDD_FSTMEAS                     260
#define IDD_RMS1                        261
#define IDD_PEAK2                       262
#define IDD_RMS2                        263
#define IDD_PEAK3                       264
#define IDD_RMS3                        265
#define IDD_BETWEEND_TEXT               265
#define IDD_LIMBTN                      270
#define IDD_WAITD_SB                    271
#define IDD_WAITD_EB                    272
#define IDD_WAITD_CB                    273
#define IDD_DUR_LAB                     274
#define IDD_PMAX_SB                     280
#define IDD_RMAX_SB                     281
#define IDD_RMIN_SB                     282
#define IDD_PMAX_EB                     283
#define IDD_RMAX_EB                     284
#define IDD_RMIN_EB                     285
#define UPDATE_NUMBERS                  290
#define UPDATE_EUT_SOURCE               291
#define IDD_ICON1                       300
#define IDD_INRUSH_POSPEAK              301
#define IDD_ICON2                       301
#define IDM_OPEN                        301
#define IDD_INRUSH_NEGPEAK              302
#define IDD_ICON3                       302
#define IDM_SAVE                        302
#define IDD_INRUSH_QUALIFY              303
#define IDD_ICON4                       303
#define IDM_SAVE_AS                     303
#define IDD_INRUSH_EXIT                 304
#define IDD_ICON5                       304
#define IDM_ABOUT                       304
#define IDD_INRUSH_STATUS               305
#define IDM_CALIBRATION                 305
#define IDD_INRUSH_EUTPOWER_GROUP       306
#define IDM_LON                         306
#define IDD_INRUSH_EUTPOWER             307
#define IDM_LOFF                        307
#define IDD_INRUSH_CHEAT                308
#define IDM_LSET                        308
#define IDM_NEW                         309
#define IDM_START                       310
#define IDM_NAME                        311
#define IDM_HELP_CONTENTS               312
#define IDD_E400DLG                     314
#define IDD_DIALOG1                     315
#define IDR_MAIN_MENU                   316
#define IDR_CAL_MENU                    317
#define IDD_ABOUT                       318
#define IDD_CHOOSE_COUPLER              319
#define IDD_CHOOSE_EFT_MODULE           320
#define IDD_ECATCOMM_RESUME             321
#define IDD_ECATCOMM_ABORT              322
#define IDD_PAUSE                       322
#define IDD_ECATCOMM_EXIT               323
#define IDD_SETUP_LOG                   323
#define IDD_COMMENT                     324
#define IDD_START_LOG                   325
#define IDD_TEST_NAME                   326
#define IDI_APP                         327
#define IDI_STOP                        328
#define IDD_INTERLOCK                   329
#define IDI_DURATION                    330
#define IDI_FREQUENCY                   331
#define IDI_EX_POINT                    332
#define IDI_SWITCH                      333
#define IDI_REPEAT                      334
#define IDI_PERIOD                      335
#define IDI_LIMIT                       336
#define IDI_NEG_V                       337
#define IDI_POS_V                       338
#define IDI_VOLTAGE                     339
#define IDI_POLARITY                    340
#define IDI_PHASE                       341
#define IDC_CUR_DURATION                342
#define IDC_CUR_FREQUENCY               343
#define IDC_CUR_NEG_V                   344
#define IDC_CUR_PERIOD                  345
#define IDC_CUR_PHASE                   346
#define IDC_CUR_POS_V                   347
#define IDC_CUR_REPEAT                  348
#define IDC_CUR_SWITCH                  349
#define IDC_CUR_VOLTAGE                 350
#define IDC_CUR_POLARITY                351
#define IDC_E400_ACL                    352
#define IDD_AC_LIMIT                    353
#define IDD_AC_MEASURE                  354
#define IDD_DUAL                        355
#define IDD_DUAL1                       356
#define IDD_DELETE                      357
#define IDD_INSERT                      358
#define IDD_EFT_COUPLE                  359
#define IDI_BUT_EXIT                    360
#define IDD_RAW_STOP_ON                 361
#define IDD_RUN_ON                      363
#define IDD_STEP_ON                     364
#define IDD_EUT_POWER_RDY               365
#define IDD_EUT_POWER_ON                366
#define IDD_GND_NEG                     367
#define IDD_GND_POS                     369
#define IDD_L1_NEG                      370
#define IDD_L1_POS                      371
#define IDD_L2_NEG                      372
#define IDD_L2_POS                      373
#define IDD_L3_NEG                      374
#define IDD_L3_POS                      375
#define IDD_N_NEG                       376
#define IDD_N_POS                       377
#define IDD_CALDIALOG                   378
#define IDD_CALIBRATE                   378
#define IDD_POLL                        379
#define IDD_PQFDLG                      380
#define IDD_PQFDLG_old                  380
#define IDD_PQFDLG1                     381
#define IDD_S1_NEG                      393
#define IDD_S1_POS                      396
#define IDD_S2_NEG                      400
#define IDD_S2_POS                      403
#define IDD_S3_NEG                      407
#define IDD_S3_POS                      410
#define IDD_S4_POS                      420
#define IDD_S4_NEG                      421
#define IDD_G_NEG                       424
#define IDD_G_POS                       427
#define IDD_COMM_LINK_MSG               428
#define IDI_COMM_LINK_2                 430
#define IDM_PQF_FILEOPEN                501
#define IDM_PQF_FILESAVE                502
#define IDM_PQF_FILESAVEAS              503
#define IDM_PQF_FILENEW                 504
#define IDM_PQF_VIEW_RESPONSE           506
#define IDM_PQF_VIEW_INSTRUMENT         507
#define IDM_PQF_VIEW_PLAN               508
#define IDM_PQF_AUTOPOPUP               511
#define IDM_PQF_AUTOPOPDOWN             512
#define IDM_PQF_GRAPH_ENABLEZOOMIN      515
#define IDM_PQF_GRAPH_DISABLEZOOMIN     516
#define IDM_PQF_GRAPH_ZOOMOUT           517
#define IDM_PQF_ABOUT                   521
#define IDM_PQF_CALIBRATION             522
#define IDM_PQF_QUALIFICATION           523
#define IDM_PQF_LON                     531
#define IDM_PQF_LOFF                    532
#define IDM_PQF_LSET                    533
#define IDB_FRM_TOTAL                   534
#define IDB_FRM_AUX                     535
#define IDC_CUR_CROSS                   536
#define IDI_ARR_DOWN                    537
#define IDI_ARR_UP                      538
#define IDD_TEST_UPLOAD                 539
#define IDD_QUALIFYING                  540
#define IDD_RUN_PREP                    1001
#define IDD_RAW_STEP                    1004
#define IDD_PHASE_MODE                  1005
#define IDD_MEASURE                     1006
#define IDC_ORDER_BASE                  1013
#define IDC_MAINFRM_BASE                1014
#define IDC_REPEAT_BASE                 1015
#define IDC_CHECK1                      1016
#define IDD_PQF_TESTREPEAT_TEXT         1016
#define IDC_RADIO1                      1017
#define IDC_RDB_OPEN                    1017
#define IDC_RDB_HUNDRED                 1018
#define IDD_SRG_COUPLE                  1021
#define IDC_EDIT_INFO                   1020
#define IDC_ILOCK_ICON                  1021
#define IDC_COMBO_LEVEL                 1023
#define IDC_SPIN_START                  1026
#define IDC_SPIN_DURATION               1027
#define IDC_SPIN_RMSI                   1028
#define IDC_SPIN_PICKI                  1029
#define IDC_SPIN_DUR_UNIT               1030
#define IDC_PQF_STATUS                  1031
#define IDC_PQF_TEST_GRP                1033
#define IDC_DUR_UNITS_TEXT              1034
#define IDC_BUT_LIST_UP                 1036
#define IDC_BUT_LIST_DN                 1037
#define IDC_BUT_QUALIFY                 1038
#define IDC_INRUSH_POS                  1039
#define IDC_INRUSH_NEG                  1040

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        541
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1041
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
