#include "lib_top.h"


#pragma	option	-nx

/************************************************************************/
/* THIS INFORMATION IS PROPRIETARY TO					*/
/* MICROTEC RESEARCH, INC.						*/
/* 2350 Mission College Blvd.						*/
/* Santa Clara, CA 95054						*/
/* USA									*/
/*----------------------------------------------------------------------*/
/* Copyright (c) 1991-1992  Microtec Research, Inc.			*/
/* ALL RIGHTS RESERVED							*/
/************************************************************************/
/*
;The software source code contained in this file and in the related
;header files is the property of Microtec Research, Inc. and may only be
;used under the terms and conditions defined in the Microtec Research
;license agreement. You may modify this code as needed but you must retain
;the Microtec Research, Inc. copyright notices, including this statement.
;Some restrictions may apply when using this software with non-Microtec
;Research software.  In all cases, Microtec Research, Inc. reserves all rights.
*/



/*	This routine tests the rand and srand functions by calling rand
	fifty times X 2 cases and comparing rand's output with the sequence
	it should generate.
*/

/*	%W% %G%	*/

#include <stdlib.h>
#include <stdio.h>

#include "message.h"

/*	First fifty random #'s generated by rand if srand is not called first */

const int noStart[] = {
		16838,
		5758,
		10113,
		17515,
		31051,
		5627,
		23010,
		7419,
		16212,
		4086,
		2749,
		12767,
		9084,
		12060,
		32225,
		17543,
		25089,
		21183,
		25137,
		25566,
		26966,
		4978,
		20495,
		10311,
		11367,
		30054,
		17031,
		13145,
		19882,
		25736,
		30524,
		28505,
		28394,
		22102,
		24851,
		19067,
		12754,
		11653,
		6561,
		27096,
		13628,
		15188,
		32085,
		4143,
		6967,
		31406,
		24165,
		13403,
		25562,
		24834};

/*	First fifty returns from rand () when srand is first called w.  31415); */

const int startM1[] = {
		1570,
		29614,
		27860,
		5528,
		23138,
		13966,
		7004,
		8462,
		17991,
		4911,
		3968,
		27451,
		7371,
		15733,
		26450,
		10095,
		25992,
		26895,
		16163,
		1290,
		25641,
		23160,
		13521,
		16090,
		10900,
		2985,
		21459,
		17464,
		8661,
		24734,
		13829,
		22497,
		13769,
		10127,
		25908,
		16533,
		3983,
		24811,
		18793,
		26482,
		2734,
		2836,
		12278,
		13,
		20742,
		28125,
		14145,
		5717,
		18808,
		8645 };

#define NUM_EL(X) (sizeof(X)/sizeof(X[0])) /* number of elememnts in array */


main ()
{
int errorCount = 0;
int i;

    for (i=0; i < NUM_EL(noStart); i++) {
	if (rand () != noStart[i]) {
	    printf ("error:  rand:  no init w srand: cycle = %d\n", i);
	    errorCount = 1;
	    break;
	    }
	}

    srand (31415);					/* init w srand */

    for (i=0; i < NUM_EL(startM1); i++) {
	if (rand () != startM1[i]) {
	    printf ("error:  rand:  init to -1 w srand: cycle = %d\n", i);
	    errorCount = 1;
	    break;
	    }
	}

    if (errorCount)
	printf (ERRORS);
    else
	printf (NO_ERRORS);
}
 
