cp1=0 | BIT_L2|(256*(0 | BIT_L3));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_L3|(256*(0 | BIT_L2));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_L1|(256*(0 | BIT_L3));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_L1|(256*(0 | BIT_L3));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_L1|(256*(0 | BIT_L2));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_L1|(256*(0 | BIT_L2));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_L1|(256*(0 | BIT_L2 | BIT_L3));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_L2|(256*(0 | BIT_L1 | BIT_L3));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_L3|(256*(0 | BIT_L1 | BIT_L2));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_N|(256*(0 | BIT_L3));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_N|(256*(0 | BIT_L3));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_N|(256*(0 | BIT_L2));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_N|(256*(0 | BIT_L2));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_N|(256*(0 | BIT_L2 | BIT_L3));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_N|(256*(0 | BIT_L2 | BIT_L3));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_N|(256*(0 | BIT_L1));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_N|(256*(0 | BIT_L1));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_N|(256*(0 | BIT_L1 | BIT_L3));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_N|(256*(0 | BIT_L1 | BIT_L3));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_N|(256*(0 | BIT_L1 | BIT_L2));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_N|(256*(0 | BIT_L1 | BIT_L2));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_N|(256*(0 | BIT_L1 | BIT_L2 | BIT_L3));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_L2|(256*(0 | BIT_N | BIT_L3));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_L3|(256*(0 | BIT_N | BIT_L2));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_L1|(256*(0 | BIT_N | BIT_L3));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_L1|(256*(0 | BIT_N | BIT_L3));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_L1|(256*(0 | BIT_N | BIT_L2));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_L1|(256*(0 | BIT_N | BIT_L2));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_L1|(256*(0 | BIT_N | BIT_L2 | BIT_L3));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_L3|(256*(0 | BIT_N | BIT_L1));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_L2|(256*(0 | BIT_N | BIT_L1));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_L2|(256*(0 | BIT_N | BIT_L1));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_L2|(256*(0 | BIT_N | BIT_L1 | BIT_L3));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_L3|(256*(0 | BIT_N | BIT_L1 | BIT_L2));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_GND|(256*(0 | BIT_L3));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_GND|(256*(0 | BIT_L3));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_GND|(256*(0 | BIT_L2));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_GND|(256*(0 | BIT_L2));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_GND|(256*(0 | BIT_L2 | BIT_L3));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_GND|(256*(0 | BIT_L2 | BIT_L3));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_GND|(256*(0 | BIT_L1));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_GND|(256*(0 | BIT_L1));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_GND|(256*(0 | BIT_L1 | BIT_L3));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_GND|(256*(0 | BIT_L1 | BIT_L3));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_GND|(256*(0 | BIT_L1 | BIT_L2));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_GND|(256*(0 | BIT_L1 | BIT_L2));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_GND|(256*(0 | BIT_L1 | BIT_L2 | BIT_L3));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_GND|(256*(0 | BIT_L1 | BIT_L2 | BIT_L3));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_GND|(256*(0 | BIT_N));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_GND|(256*(0 | BIT_N));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_GND|(256*(0 | BIT_N | BIT_L3));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_GND|(256*(0 | BIT_N | BIT_L3));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_GND|(256*(0 | BIT_N | BIT_L2));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_GND|(256*(0 | BIT_N | BIT_L2));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_GND|(256*(0 | BIT_N | BIT_L2 | BIT_L3));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_GND|(256*(0 | BIT_N | BIT_L2 | BIT_L3));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_GND|(256*(0 | BIT_N | BIT_L1));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_GND|(256*(0 | BIT_N | BIT_L1));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_GND|(256*(0 | BIT_N | BIT_L1 | BIT_L3));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_GND|(256*(0 | BIT_N | BIT_L1 | BIT_L3));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_GND|(256*(0 | BIT_N | BIT_L1 | BIT_L2));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_GND|(256*(0 | BIT_N | BIT_L1 | BIT_L2));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
cp1=0 | BIT_GND|(256*(0 | BIT_N | BIT_L1 | BIT_L2 | BIT_L3));
SendDlgItemMessage(hDlg,IDD_LIST,LB_INSERTSTRING,1,cp1);
